# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class Test():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_(self):
    # Test name: 登录
    # Step # | name | target | value | comment
    # 1 | open | http://59.202.45.151:9090/pubdle/login |  | 
    self.driver.get("http://59.202.45.151:9090/pubdle/login")
    # 2 | setWindowSize | 1052x692 |  | 
    self.driver.set_window_size(1052, 692)
    # 3 | click | id=username |  | 
    self.driver.find_element(By.ID, "username").click()
    # 4 | type | id=username | 18419970001 | 
    self.driver.find_element(By.ID, "username").send_keys("18419970001")
    # 5 | type | id=password | a123456 | 
    self.driver.find_element(By.ID, "password").send_keys("a123456")
    # 6 | click | css=.submit |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".submit").click()
    # 7 | close |  |  | 
    self.driver.close()
  
