# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class Test():
    def setup_method(self, method):
		self.driver = webdriver.Firefox()
		self.vars = {}
  
	def teardown_method(self, method):
		self.driver.quit()
  
	def test_(self):
		self.driver.get("http://59.202.45.151:9090/pubdle/login")
		self.driver.set_window_size(1052, 692)
		self.driver.find_element(By.ID, "username").click()
		self.driver.find_element(By.ID, "username").click()
		self.driver.find_element(By.ID, "username").send_keys("18419970001")
		self.driver.find_element(By.ID, "password").send_keys("a123456")
		self.driver.find_element(By.CSS_SELECTOR, ".submit").click()
		self.driver.find_element(By.CSS_SELECTOR, ".new-case").click()
		element = self.driver.find_element(By.ID, "main_center_panel")
		actions = ActionChains(driver)
		actions.move_to_element(element).perform()
		element = self.driver.find_element(By.CSS_SELECTOR, "body")
		actions = ActionChains(driver)
		actions.move_to_element(element, 0, 0).perform()
		self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(1) > .combo:nth-child(2) > .combo-text").click()
		self.driver.find_element(By.ID, "_easyui_combobox_i41_3").click()
		self.driver.find_element(By.CSS_SELECTOR, "div > .combo:nth-child(4) > .combo-text").click()
		self.driver.find_element(By.ID, "_easyui_combobox_i42_1").click()
		self.driver.find_element(By.CSS_SELECTOR, ".right-content > .combo > .combo-text").click()
		self.driver.find_element(By.ID, "_easyui_combobox_i39_3").click()
		self.driver.find_element(By.ID, "occurTime_temp").click()
		self.driver.switch_to.frame(3)
		self.driver.find_element(By.ID, "dpOkInput").click()
		self.driver.switch_to.default_content()
		self.driver.find_element(By.LINK_TEXT, "[ 添加 ]").click()
		self.driver.find_element(By.ID, "name").click()
		self.driver.find_element(By.ID, "name").send_keys("test0807001")
		self.driver.find_element(By.CSS_SELECTOR, ".combo-arrow-hover").click()
		self.driver.find_element(By.ID, "_easyui_combobox_i43_0").click()
		self.driver.find_element(By.CSS_SELECTOR, ".combo-arrow-hover").click()
		self.driver.find_element(By.ID, "_easyui_combobox_i43_1").click()
		self.driver.find_element(By.ID, "idcard").click()
		self.driver.find_element(By.ID, "idcard").send_keys("12121212")
		self.driver.find_element(By.CSS_SELECTOR, "#test tr:nth-child(14) > td:nth-child(2)").click()
		self.driver.find_element(By.ID, "tel").click()
		self.driver.find_element(By.ID, "tel").send_keys("18419985554")
		self.driver.find_element(By.ID, "workunit").click()
		self.driver.find_element(By.ID, "workunit").send_keys("2")
		self.driver.find_element(By.ID, "address").click()
		self.driver.find_element(By.ID, "address").send_keys("3")
		self.driver.find_element(By.ID, "address1").click()
		self.driver.find_element(By.ID, "address1").send_keys("4")
		self.driver.find_element(By.CSS_SELECTOR, ".lawbreaker-btn").click()
		self.driver.find_element(By.ID, "lexinfoCode").click()
		element = self.driver.find_element(By.ID, "lexinfoCode")
		actions = ActionChains(driver)
		actions.move_to_element(element).perform()
		element = self.driver.find_element(By.CSS_SELECTOR, "body")
		actions = ActionChains(driver)
		actions.move_to_element(element, 0, 0).perform()
		self.driver.find_element(By.ID, "lexinfoCode").click()
		element = self.driver.find_element(By.LINK_TEXT, "[ 选择 ]")
		actions = ActionChains(driver)
		actions.move_to_element(element).release().perform()
		self.driver.find_element(By.LINK_TEXT, "[ 选择 ]").click()
		self.driver.switch_to.frame(3)
		self.driver.switch_to.frame(0)
		self.driver.find_element(By.CSS_SELECTOR, "#datagrid-row-r1-2-0 .datagrid-cell-c1-code").click()
		self.driver.find_element(By.CSS_SELECTOR, "#datagrid-row-r1-2-0 .datagrid-cell-c1-name").click()
		self.driver.find_element(By.CSS_SELECTOR, "#datagrid-row-r1-2-0 .datagrid-cell-c1-name").click()
		element = self.driver.find_element(By.CSS_SELECTOR, "#datagrid-row-r1-2-0 .datagrid-cell-c1-name")
		actions = ActionChains(driver)
		actions.double_click(element).perform()
		self.driver.find_element(By.CSS_SELECTOR, "#datagrid-row-r1-2-0 .datagrid-cell-c1-code").click()
		self.driver.find_element(By.CSS_SELECTOR, "#datagrid-row-r1-2-0 .datagrid-cell-c1-code").click()
		element = self.driver.find_element(By.CSS_SELECTOR, "#datagrid-row-r1-2-0 .datagrid-cell-c1-code")
		actions = ActionChains(driver)
		actions.double_click(element).perform()
		self.driver.find_element(By.CSS_SELECTOR, "#datagrid-row-r1-2-0 .datagrid-cell-c1-code").click()
		self.driver.find_element(By.CSS_SELECTOR, "#datagrid-row-r1-2-0 .datagrid-cell-c1-code").click()
		self.driver.find_element(By.CSS_SELECTOR, "#datagrid-row-r1-2-0 .datagrid-cell-c1-code").click()
		element = self.driver.find_element(By.CSS_SELECTOR, "#datagrid-row-r1-2-0 .datagrid-cell-c1-code")
		actions = ActionChains(driver)
		actions.double_click(element).perform()
		self.driver.switch_to.default_content()
		self.driver.switch_to.default_content()
		self.driver.find_element(By.LINK_TEXT, "[ 生成简介 ]").click()
		self.driver.find_element(By.ID, "btnSave_add").click()

